### ISSUE TITLE
Version inconsistency in RSS Plugin

### ISSUE THREAD

**Issue by fthommen** [algorys/rss#2]
Will you fix this?

> On 06/03/2016 06:50 PM, Matt Algorythm wrote:
> 
> > Hello.
> > 
> > Yes it's just an error of dokuwiki website and my repository.
> > 
> > No new version actually.
> > 
> > Please report future issue on github :)
> > 
> > Thanks
> > 
> > Le 3 juin 2016 17:20, "Frank Thommen" <f.thommen@dkfz-heidelberg.de 
> > <mailto:f.thommen@dkfz-heidelberg.de>> a écrit :
> > 
> > ```
> > Hi,
> > 
> > we habe installed the newest RSS plugin.  The version installed
> > reports to be "2016-01-20" and the Extension Manager reports, that
> > there is a newer version "2016-01-21".  However the update always
> > leads to version "2016-01-20".
> > 
> > Cheers
> > Frank
> > ```

**Comment by algorys** [comment]
Normally, that's done.
