### ISSUE TITLE
Feature request:  Add localization

### ISSUE THREAD

**Issue by jFMd21** [algorys/rss#3]
Hello Matt,

could you pls. add localization options for the plugin as described in https://www.dokuwiki.org/devel:localization#plugin_localization

This would allow to add additional languages to your plugin to display the so far only French text displayed by the plugin in the Wiki's language. E.g. in the example below "publié le 10/03/2017 à 10h46" should be printed in German...

![image](https://cloud.githubusercontent.com/assets/26376634/23857963/462165f2-07ff-11e7-8741-d5774123bd97.png)

I would love to contribute en, de and de-informal...

Cheers,
fmd

**Comment by jFMd21** [comment]
If you then also would register the plugin in the DokuWiki Translation Tool (https://translate.dokuwiki.org/plugin) it would be highly appreciated!  :-)

**Comment by algorys** [comment]
@jFMd21 great idea.

I think to get back to work on dokuwiki plugins soon, so I'll try to do that ASAP.

**Comment by algorys** [comment]
@jFMd21 I've added plugin in the DokuWiki Translation Tool :wink:

**Comment by jFMd21** [comment]
@algorys Thanks Matthieu, but I am not sure if this will work right away. I'm not a programmer and don't understand very much coding, but I guess, your plugin does not fully meet the requirements from https://www.dokuwiki.org/devel:localization#plugin_localization...

**Comment by algorys** [comment]
@jFMd21 you're right... I'll do the job, no problem.

**Comment by jFMd21** [comment]
@algorys Salut Matthieu, last night I finally found that DokuWiki can display RSS feeds itself already (https://www.dokuwiki.org/rss). I actually had been supposing this, but had not found out how so far.
Since this is already built in, your plugin is actually not necessary anymore - I can not see an advantage in using it.
So sorry - and thank you for your effort!! - I won't use your plugin anymore. But anyhow, if you'd still like implement the localization option, I'll stick to my promise and add at least German translation to it...

**Comment by algorys** [comment]
Done.
